apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: refinery-api
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "10"
        run.googleapis.com/cpu-throttling: "true"
    spec:
      containerConcurrency: 80
      containers:
      - image: refinery-api-image
        resources:
          limits:
            cpu: "2"
            memory: "1Gi"
